### ISSUE TITLE
sdk.config

### ISSUE THREAD

**Issue by khs1994** [tencentyun/wafer2-quickstart-php#1]
https://github.com/tencentyun/wafer2-quickstart-php/blob/f4ba8f78cd3d7b4ae20cba76f02c5188df0a0184/server/install_qcloud_sdk.php#L14

为什么windows是`sdk.config`
linux 是`sdk.config.json`
能统一一下吗

**Comment by khs1994** [comment]
#2

**Comment by jas0ncn** [comment]
不是的。这是 wafer2 的 demo，sdk.config.json 是我们统一下发到机器上的，和 wafer1 的 sdk.config 不一样的，请不要修改这个文件的路径，目前我们还不支持 windows，代码里面的 windows 路径暂时还没有确定。
