### ISSUE TITLE
请更新配置文件 server/config.php

### ISSUE THREAD

**Issue by khs1994** [tencentyun/wafer2-quickstart-php#3]
https://cloud.tencent.com/document/product/619/12797

**Comment by khs1994** [comment]
https://github.com/tencentyun/wafer2-quickstart-php/blob/master/server/config.php

**Comment by jas0ncn** [comment]
是这样的，我们会在生产环境和开发环境初始化的时候，将配置写入到 /data/release/sdk.config.json 文件中，运行时会自动导入，参考：https://github.com/tencentyun/wafer2-quickstart-php/blob/master/server/install_qcloud_sdk.php#L20
