### ISSUE TITLE
d登录失败

### ISSUE THREAD

**Issue by sjtuzhangbenxuan** [tencentyun/wafer2-quickstart-php#9]
![default](https://user-images.githubusercontent.com/36227079/40666125-95e06996-6391-11e8-810a-425a5b9aee91.png)

**Comment by jas0ncn** [comment]
mysql 的密码没有修改哈，修改 `server/config.js` 里的 `mysql.pass` 一项为你的小程序 AppID，另外要记得保存和上传。
